### PR TITLE
Add predicate descriptions overloads to anyMatch and noneMatch

### LINKED ISSUE #3638: Allow supplying predicate description to `anyMatch` and `noneMatch`
#### Feature summary
It would be helpful to be able to supply a custom predicate description to all predicate-based iterable assertions (`allMatch`, `anyMatch` and `noneMatch`). Currently only `allMatch` allows supplying a custom predicate description.

From [the docs](https://assertj.github.io/doc/#match) (under the example for all 3):
> "You can pass a predicate description to make the error message more explicit if the assertion fails" under the example of all three.

It would be good to keep the docs aligned to the functionality, although in this case aligning the functionality to the docs would be preferable.

#### Example
```java
List<String> myList = List.of("a", "b", "cc");
assertThat(myList).allMatch(entry -> entry.length() == 2, "length of 2"); // ✅
assertThat(myList).anyMatch(entry -> entry.length() == 2, "length of 2"); // ❌
assertThat(myList).noneMatch(entry -> entry.length() == 2, "length of 2"); // ❌
```

### PR DESCRIPTION
**Pull request by jh-instant**
#### Check List:
* Fixes #3638 
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) : I think so!

Hopefully fairly self explanatory. Happy to make any necessary changes. Not sure how to calculate the `@since` field on the Javadoc, so took a guess at the next minor version.

### CODE REVIEW

**Comment by jh-instant** [comment]
Spotted the build was failing. Might be handy to have a bullet point to say "run `./mvnw spotless:apply`" in the contributing doc - I wasn't aware this was a thing

**Comment by scordio** [comment]
Hi @jh-instant, thanks a lot for raising the PR! I'm sorry it might take a bit longer before we can review the changes.

If you participate in Hacktoberfest, I will label the PR as accepted so that it is properly counted.

**Comment by jh-instant** [comment]
No problem - take your time. Looks like I needed to rebase to fix this test:

> [ERROR]   DurationAssert_isZero_Test.should_fail_if_actual_is_not_zero:47 
> Expecting message to be:
>   "
> expected: 0S
>  but was: -1S"
> but was:
>   "
> expected: 0S
>  but was: -1S"

I guess the workflows will need running again, sorry!

**Comment by joel-costigliola** [comment]
Integrated thanks @jh-instant!

**Pull request closed without merging**
