### PR TITLE
#2530: Add spotless check for formatting preferences

### LINKED ISSUE #2530: Spotless check for formatting preferences
#### Summary

I noticed that in your `CONTRIBUTING.md` file, you mention to use Eclipse formatting preferences and there is an Eclipse Formatter file with all the rules defined. However, the style of the code is not actually checked with the Continuous Integration workflows. 

Since the Eclipse Formatter file with all the rules already exists, it should be pretty straightforward to use [spotless](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md) - this could then be used as a maven command by users and it could be easily integrated as another workflow to check PRs. 

Let me know if this is something that you'd want for the project, I would love to pick it up :)

### PR DESCRIPTION
**Pull request by hjir**
#### Check List:
* Fixes #2530 
* Unit tests : NA
* Javadoc with a code example (on API only) : NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) ✅ 

All the changes relevant to adding the spotless dependency are in the first commit ([48a9b14](https://github.com/assertj/assertj-core/pull/2533/commits/48a9b14e72059d5859cbdd0d8ee786d4c21ff1f4)) - I suggest looking at that instead of all the changes that resulted from applying spotless. Apart from adding the spotless dependency and a github workflow, I also added information about spotless to the contributing guidelines.

### CODE REVIEW

**Comment by hjir** [comment]
@scordio I picked this up from #2530 but now the pitest pipeline is failing (from what I saw in the logging, there seems to be an `OutOfMemoryError`). do you have any pointers on what I can do about this?

**Comment by scordio** [comment]
There is nothing wrong with your changes, it's rather a general problem we have with pitest. Feel free to ignore that failure.

**Comment by hjir** [comment]
> There is nothing wrong with your changes, it's rather a general problem we have with pitest. Feel free to ignore that failure.

alright, thanks! in that case this PR is ready for review :)

**Comment by joel-costigliola** [comment]
I'm not opposed to applying spotless but I think we need to make the spotless config as close as possible to our existing formatting preferences, there are too many changes in this PR.

**Comment by scordio** [comment]
Superseded by #3115.

**Pull request closed without merging**
