### PR TITLE
Add AbstractCompletableFutureAssert.completesExceptionallyWithin

### LINKED ISSUE #3587: Confusing behavior of AbstractCompletableFutureAssert.failsWithin
**Describe the bug**

Sometimes I need to verify that the future completed with exception, but don't care with which exactly.
Used `assertThat(future).failsWithin(...)` for that. But, to my greatest surprise, found that `assertThat(future).failsWithin(...)` passes when the future doesn't complete at all, neither successfully, nor exceptionally.

* assertj core version: 3.26.3
* java version: 17
* test framework version: junit 5

**Test case reproducing the bug**

```java
    // a future that doesn't complete
    CompletableFuture<Void> future = new CompletableFuture<>();
    // the next assertion passes as if future has failed --- this is counterintuitive
    assertThat(future).failsWithin(Duration.ofMillis(100));
    // the next assertion fails, because the future hasn't actually failed --- this makes sense
    assertThat(future).hasFailed();
```

### PR DESCRIPTION
**Pull request by vladykin**
Issue #3587

#### Check List:
* Fixes #3587
* Unit tests : YES
* Javadoc with a code example (on API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks @vladykin, I'll review the PR this week end.

**Comment by vladykin** [comment]
Fixed code formatting that spotless plugin was complaining about

**Comment by vladykin** [comment]
Things that I wasn't sure about and haven't yet included:
* separate assertion failure message in case of InterruptedException (it's currently the same message for all failures);
* note about interaction with soft assertions in the javadoc for the new methods;
* similar methods in AbstractFutureAssert.

**Comment by vladykin** [comment]
@joel-costigliola, any feedback on this PR?

**Comment by joel-costigliola** [comment]
I'll have a look this week

**Comment by joel-costigliola** [comment]
commented thanks @vladykin

**Comment by vladykin** [comment]
@joel-costigliola, I don't see any comments here. Where can I find them?

I see some failed CI jobs, but there are no details besides "This job failed", so I don't know what to do, and whether it's related to my PR or not.

**Comment by joel-costigliola** [comment]
My bad I did confirm my review so my comments were pending

**Comment by joel-costigliola** [comment]
the issues are not related to your PR, I reran the ubuntu job and it succeeded so all good

**Comment by vladykin** [comment]
Thanks for the comments, addressed

**Comment by joel-costigliola** [comment]
Integrated thanks @vladykin !

**Pull request closed without merging**
