### PR TITLE
fix: Avoid `InputStream` manipulation when `mark` / `reset` are supported

### LINKED ISSUE #2596: `InputStream` supporting `mark` / `reset` should not be manipulated by assertions
Related to https://github.com/assertj/assertj-core/issues/2490#issuecomment-1035488261, the assertions of `AbstractInputStreamAssert` could avoid manipulating the stream position when the `InputStream` implementation supports [`mark`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#mark-int-) / [`reset`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#reset--) operations, tested by [`markSupported`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#markSupported--).

### PR DESCRIPTION
**Pull request by jessicant**
#### Check List:
* Fixes #2596 
* Unit tests :  NO
* Javadoc with a code example (on API only) : NO
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

This branch is failing tests. The idea for measuring `readLimit` is the `InputStream.available()` but it is causing `AbstractInputStreamAssert.java`'s `hasDigest` method to be unhappy - `Unhandled exception: java.io.IOException`. I am confused since `tryStreamReset` is catching that exception, so I am not sure why it is not bubbling up. I think this issue is probably simple, but any help would be much appreciated :)

### CODE REVIEW

**Comment by nith2001** [comment]
I think I fixed the IOException thing, but we probably have to deal with it no matter what since reset() has a potential IOException that needs to be caught as well, not just the available() function.

**Comment by nith2001** [comment]
Screen Shot 2022-05-07 at 9 05 32 AM
Here are the tests we're failing. Keeping them here so that we have a place to reference them

**Comment by nith2001** [comment]
Ok, turns out we needed to have an assertNotNull(info, actual) statement within the assertHasDigest(). I wonder if we need it for the other assertHasDigest() function variations.

**Comment by nith2001** [comment]
Hi @scordio, I remember under the issue comments you said the following

> the mark/reset pair should be pushed down to InputStreams, being an implementation detail of the assertions

However, @jessicant and I have found including the private helper method for resetting the stream under `AbstractInputStreamAssert.java` rather than under `InputStreams.java` makes it much easier work with, since it allows to insert the `InputStreams.java` functions within the Runnable object and call them accordingly.

Is there a better reason for why this shouldn't happen?

**Comment by nith2001** [comment]
Any updates on what the next steps can be?

**Comment by scordio** [comment]
@nith2001, as mentioned in the other PR, we are now focusing on releasing 3.23.0 and we will come back to new features once done with that.

**Comment by scordio** [comment]
@jessicant @nith2001 sorry for making you wait so long!

The base branch has now evolved so I had in mind to cherry-pick your changes, but I also noticed there is still some work to do to properly update all the `InputStream` assertions.

Would you still be interested in continuing this change? If not, we can take it over and keep you as authors.

**Comment by nith2001** [comment]
Ahh, sorry, I don't think I'll have the time for this, but thank you!

**Comment by scordio** [comment]
Superseded by #3713.

**Pull request closed without merging**
