### PR TITLE
Add "it" infrastructure for integration tests

### PR DESCRIPTION
**Pull request by sormuras**
This PR adds an optional [maven-invoker-plugin](https://maven.apache.org/plugins/maven-invoker-plugin/) based profile to the build configuration that builds a set of Maven projects located in the newly added `"src/it"` directory.

No dedicated verification script is evaluated after such an `"it"` project build for the time being. A successful build is considered as successful test case.

### CODE REVIEW

**Comment by scordio** [comment]
@sormuras new release just merged in 71dc3ff90db580f42f05935f402afd7d1f229237

**Comment by sormuras** [comment]
Alright. Will perform the pending tasks today.

**Comment by sormuras** [comment]
Let's see what the CI run says...

Note: I had trouble using the `maven-surefire-plugin` to get tests run on the module-path. Therefore, I switched to an external JUnit Platform launching plugin named `junit-platform-maven-plugin` for the time being. As I actively maintain the latter and listen closely to changes/fixes applied to the former, I'll be able to switch back to the `maven-surefire-plugin` a) if possible and b) if wanted.

**Comment by scordio** [comment]
Hey @sormuras! I'm finally getting back to your PR.

This one is most likely superseded by #2759 mostly because of IDE friendliness, although I've just hit a [fancy issue](https://youtrack.jetbrains.com/issue/IDEA-301032) with IDEA.

**Comment by sormuras** [comment]
_What is "JPMS"? I am only aware of "Java modules". (-:_

**Comment by scordio** [comment]
> _What is "JPMS"? I am only aware of "Java modules". (-:_

It's a weird acronym I read on a [blog](https://nipafx.dev/five-command-line-options-hack-java-module-system/) 😀

**Comment by sormuras** [comment]
- https://twitter.com/mreinhold/status/994669659029999616
- https://twitter.com/mreinhold/status/994677111251243010

On topic: feel free to close this superseded pull request.

**Comment by scordio** [comment]
> _What is "JPMS"? I am only aware of "Java modules". (-:_

Who said _JPMS_? I obviously said _module path_ 🙂

**Comment by sormuras** [comment]
> It's a weird acronym I read on a [blog](https://nipafx.dev/five-command-line-options-hack-java-module-system/) 😀

There is no spoon. And there is no JPMS in the blog either... 🤓

**Comment by scordio** [comment]
> There is no spoon. And there is [no JPMS in the blog](https://github.com/nipafx/nipafx.dev/commit/6b0ef352580edfae7ed65b35aea2e4a1489d07d4) either... 🤓

I've already taken the red pill, so I see [how deep the rabbit hole goes](https://www.google.com/search?client=firefox-b-d&q=jpms+site%3Anipafx.dev)...

**Pull request closed without merging**
