### PR TITLE
Make it clear for java classes recursive comparison

### PR DESCRIPTION
**Pull request by FlorianCousin**
#### Check List:
- [x] Unit tests : YES
- [x] Javadoc with a code example (on API only) : NA
- [x] PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md)

Types from java package are not comparable with recursive comparison.

To prevent developers from wasting time looking for the problem, this PR adds an explicit log.
To do so, an element is added in additionalInformation in differences when needed.

This PR does not change the behavior.

Logs before :
```
Top level actual and expected objects differ:
- actual value  : IntSummaryStatistics{count=0, sum=0, min=2147483647, average=0.000000, max=-2147483648} (IntSummaryStatistics@163e4e87)
- expected value: IntSummaryStatistics{count=0, sum=0, min=2147483647, average=0.000000, max=-2147483648} (IntSummaryStatistics@56de5251)
```

Logs after :
```
Top level actual and expected objects differ:
- actual value  : IntSummaryStatistics{count=0, sum=0, min=2147483647, average=0.000000, max=-2147483648} (IntSummaryStatistics@423e4cbb)
- expected value: IntSummaryStatistics{count=0, sum=0, min=2147483647, average=0.000000, max=-2147483648} (IntSummaryStatistics@6e16b8b5)
Comparison objects are of Java types and were then compared with equals method
```

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks @FlorianCousin, I will review your PR shortly !

**Comment by FlorianCousin** [comment]
The error I found in `OS ubuntu-latest` failed job is as follows.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:javadoc (default-cli) on project assertj-guava: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1
[ERROR] error: Error fetching URL: https://javadoc.io/doc/com.google.guava/guava/32.1.2-jre/ (java.io.IOException: Server returned HTTP response code: 521 for URL: https://javadoc.io/doc/com.google.guava/guava/32.1.2-jre/package-list)
[ERROR] error: Error fetching URL: https://javadoc.io/doc/org.assertj/assertj-core/3.25.0-SNAPSHOT/ (java.io.IOException: Server returned HTTP response code: 521 for URL: https://javadoc.io/doc/org.assertj/assertj-core/3.25.0-SNAPSHOT/package-list)
```
The URL `https://javadoc.io/doc/com.google.guava/guava/32.1.2-jre/` is indeed not accessible.
I guess the problem is not caused by my PR but then I don't know how to fix it.

Do you have any idea ?
Could you please launch the workflows again now I rebased on main ?

**Comment by scordio** [comment]
javadoc.io should be back now so there shouldn't be failures anymore

**Comment by FlorianCousin** [comment]
@joel-costigliola @scordio 
I updated my branch by rebasing onto assertj/main and there is no conflict anymore.
Would you please launch the workflows ?

**Comment by FlorianCousin** [comment]
2 tests have been fixed.
I think workflows can be launched again.
Sorry I had not checked the tests on my own machine before.

**Comment by FlorianCousin** [comment]
An error occured during 'Upload reports" :
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

I guess it is independant of my code changes because it looks linked to the workflows itself.

**Comment by joel-costigliola** [comment]
it is @FlorianCousin

**Comment by joel-costigliola** [comment]
Integrated thanks @FlorianCousin !

**Comment by FlorianCousin** [comment]
> Integrated thanks @FlorianCousin !

This is a great news, thank you.

**Pull request closed without merging**
