### PR TITLE
Add `isExecutable` to `File` assertions

### PR DESCRIPTION
**Pull request by rostIvan**
#### Check List:
* Related to #2205
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md)

#### Examples:
```java
File tmpFile = java.nio.file.Files.createTempFile("executable_file", ".sh").toFile();

tmpFile.setExecutable(true);
// assertions will pass
assertThat(tmpFile).isExecutable();

tmpFile.setExecutable(false);
// assertions will fail
assertThat(tmpFile).isExecutable();
```

### CODE REVIEW

**Review by joel-costigliola — CHANGES_REQUESTED** [review]
Thanks @rostIvan, first round of code review done.

**Comment by scordio** [comment]
**Team decision**: let's add `isExecutable` only.

**Comment by rostIvan** [comment]
Hi @joel-costigliola, added `isExecutable` only.
Please take a look.

**Comment by joel-costigliola** [comment]
Integrated thanks @rostIvan!

**Pull request closed without merging**
