### PR TITLE
Fix javadoc options / Use legacy mode to overcome <source> level issue

### PR DESCRIPTION
**Pull request by hazendaz**
- options need to have additional arguments as an array rather than string
- removed old source 8 on javadocs as no longer needed here.
- Per javadoc 3.6.0 plugin, maven introduced ```<legacyMode>``` which overcomes bugs with javadocs that prevented source from being set higher as documented [here](https://github.com/assertj/assertj/issues/1403).  To replace the source attribute this is set to 'true'

### CODE REVIEW

**Comment by scordio** [comment]
Hi @hazendaz, sorry for getting back to you so late!

Some of your changes have been applied as part of #3324. Still, I would apply the changes for `additionalOptions` you proposed.

However, I'm unsure if [`legacyMode`](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#legacyMode) is required. The build already excludes the module path and we haven't noticed any side effects since #3324.

**Comment by hazendaz** [comment]
closing this, will open new one separately against main.

**Comment by hazendaz** [comment]
@scordio How exactly is modular path excluded?  Javadoc have always ran modular checks.  The legacyMode flag (poorly named) disables that.

**Comment by hazendaz** [comment]
Rebased this and created new PR to main since this got switched to 3.x since last time it was worked on.

**Pull request closed without merging**
