### PR TITLE
Add building block to create custom precise assertions

### PR DESCRIPTION
**Pull request by alex859**
#### Check List:
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

The goal is to be able to make precise soft assertions on complex objects (i.e. where we don't need to assert the equality of the full object) and to have easy to read test code and assertion error messages.

Example:

```java
assertThat(customer).is(
    customer(
        name(
            first("Boris"),
            last("Johnson")),
            address(
                firstLine("10, Downing Street"),
                postcode("SW2A 2AA")
         )
    )
)
``` 

and on failure get an error message like:

```
[✗] customer:[
   [✗] name:[
      [✓] first: Boris,
      [✗] last: Johnson but was Johnstone
   ],
   [✗] address:[
      [✓] first line: 10, Downing Street,
      [✗] postcode: SW2A 2AA but was SW1A 2AA
   ]
```

I tried using custom soft assertions, but I found the error message to be less readable (and the implementation more complex).
Maybe there is already another way to achieve this?

Also `NestableCondition` is not a great name :relaxed:.

Looking forward to getting your feedback.

Thanks!

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks @alex859 , I will review your PR in the next couple weeks!

**Comment by vlsi** [comment]
This assertion API looks lika Hamcrest, and it is known for its poor discoverability.
In other words, developer who writes `customer(` has no possibility to figure out the available continuations.

Have you considered using lambdas instead of nesting function results? Even though Java's nested lambdas are a bit verbose, they are discoverable.

E.g.
```
assertThat(customer).is(c -> {
    c.name.is(n -> {
        n.first.isEqualTo("Boris") // this allows to use full AssertJ power
        n.last("Jonson") // it might be helpful for literals
    })
})
```

With Kotlin, it would become

```
assertThat(customer).`is` { // "is" is reserved, so alternative is required
    name.`is` {
        first.isEqualTo("Boris") // this allows to use full AssertJ power
        last("Jonson") // it might be helpful for literals
    }
}
```

The key difference from the proposal in PR is that users get autocomplete after they type `c.`

**Comment by joel-costigliola** [comment]
Integrated thanks @alex859!

**Comment by alex859** [comment]
Thanks @joel-costigliola!

**Comment by alex859** [comment]
@vlsi Thanks for your comment! I'm not sure how the first Java example could be implemented, what type is `c.name`?

Kotlin devs can define a DSL to build nestable conditions that are discoverable.
Something like:

```kotlin
@DslMarker
annotation class CustomerDsl

@CustomerDsl
class CustomerConditions {
    private val conditions = mutableListOf<Condition<Customer>>()

    fun name(nameConditions: NameConditions.() -> Unit) {
        conditions += NameConditions().apply(nameConditions).build()
    }

    fun build(): Condition<Customer> =
        nestable("customer", *conditions.toTypedArray())
}

@CustomerDsl
class NameConditions {
    private val conditions = mutableListOf<Condition<Name>>()

    fun first(expected: String) {
        conditions += verboseCondition(
            { expected == it.first },
            "first: $expected",
            { " but was ${it.first}" }
        )
    }

    fun last(expected: String) {
        conditions += verboseCondition(
            { expected == it.last },
            "last: $expected",
            { " but was ${it.last}" }
        )
    }

    fun build(): Condition<Customer> =
        nestable("name", { it.name }, *conditions.toTypedArray())
}
```
And then use `invoke` as you suggested


```kotlin
operator fun ObjectAssert<Customer>.invoke(
    conditions: CustomerConditions.() -> Unit
): ObjectAssert<Customer> =
    `is`(CustomerConditions().apply(conditions).build())
```
to get:

```kotlin
(assertThat(customer)) {
    name {
        first("Boris")
        last("Unknown")
    }
}
```

**Comment by vlsi** [comment]
>Kotlin devs can define a DSL to build nestable conditions that are discoverable.

@alex859 , I guess the same (or even better DSL) can be created without resorting to `Condition` and `Nestable`.
Already existing `assertSoftly` is more-or-less fine for creating DSL like you suggested, and the implementation would not be limited by the small amount of existing `Condition` implementations.

**Comment by alex859** [comment]
@vlsi the main advantage of the proposed approach is that on failure the error message is more readable.

**Comment by vlsi** [comment]
Technically speaking, "address" string should come together with function that extracts the address. Otherwise it is just wrong to link "address" and allOf.
There might be anyOf, noneOf, and so on, so labelling allOf with "address" is wrong.

If the functions are labelled properly, then the library can produce nice messages.

**Pull request closed without merging**
