### PR TITLE
Add doesNotThrowAnyExceptionExcept to AbstractThrowableAssert

### LINKED ISSUE #3248: Suggesting a doesNotThrowAnyExceptionExcept(...) method
#### Feature summary

As discussed in [another issue](https://github.com/assertj/assertj/issues/2517#issuecomment-1788856623), here is the suggestion to support being able to ignore certain exceptions when not expecting exceptions.

It would be similar to what can be done with the [Selenium API](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html):

```java
   // Waiting 30 seconds for an element to be present on the page, checking
   // for its presence once every 5 seconds.
   Wait<WebDriver> wait = new FluentWait<WebDriver>(driver)
       .withTimeout(Duration.ofSeconds(30L))
       .pollingEvery(Duration.ofSeconds(5L))
       .ignoring(NoSuchElementException.class);
```

#### Example

That is how it can look in AssertJ:

```java
assertThatCode(() -> { thisFunctionDoesNothing(); })
                .doesNotThrowAnyExceptionExcept(NoSuchElementException.class, IOException.class);
```

### PR DESCRIPTION
**Pull request by pbacz**
#### Check List:
* Fixes #3248
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

### CODE REVIEW

**Comment by pbacz** [comment]
Hi @joel-costigliola 
Do you have any comments regarding the wording of javadoc / error message?

**Comment by pbacz** [comment]
@joel-costigliola @scordio 
Is there a plan to add this to any of the milestones?

**Comment by scordio** [comment]
Done @pbacz 😉

**Comment by joel-costigliola** [comment]
Integrated thanks @pbacz!

**Pull request closed without merging**
